---

name: Publish to Maven Central
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JVM 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B package
      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      - name: Set up Maven Central
#        uses: actions/setup-java@v4
#        with:
#          java-version: 21
#          distribution: 'temurin'
#          cache: 'maven'
#          server-id: "maven-central"
#          server-username: MAVEN_USERNAME
#          server-password: MAVEN_CENTRAL_TOKEN
#          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
#          gpg-passphrase: MAVEN_GPG_PASSPHRASE
#
#      - name: Publish to Maven Central
#        run: mvn -B deploy
#        env:
#          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
#          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
#          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
